/* Mock contact database — persisted in localStorage */
const STORAGE_KEY = 'wa-crm-contacts';

const DEFAULT_CONTACTS = [
  {
    id: 'MOB-001',
    profilePicture: '',
    status: 'Active',
    sourceChannel: 'Website Lead',
    salutation: 'Mr.',
    firstName: 'Arjun',
    lastName: 'Mehta',
    fullName: 'Mr. Arjun Mehta',
    gender: 'Male',
    dateOfBirth: '1988-03-15',
    maritalStatus: 'Married',
    nationality: 'Indian',
    language: 'English, Hindi',
    religion: 'Hindu',
    mobileNumber: '+91 98765 43210',
    alternateMobileNumber: '+91 91234 56789',
    emailAddress: 'arjun.mehta@example.com',
    alternateEmailAddress: 'arjun.personal@gmail.com',
    currentAddress: { line1: '42 Skyline Residency', line2: 'Bandra Kurla Complex', line3: 'Near Trade Centre', city: 'Mumbai', state: 'Maharashtra', country: 'India', zipCode: '400051' },
    permanentAddressSameAsCurrent: false,
    permanentAddress: { line1: '15 Green Park Colony', line2: 'Sector 12', line3: '', city: 'Pune', state: 'Maharashtra', country: 'India', zipCode: '411014' },
    organization: 'TechNova Solutions',
    designation: 'Senior Product Manager',
    occupation: 'Product Management',
    industryType: 'Information Technology',
    experienceYears: 12,
    experienceMonths: 6,
    primaryExpertise: 'SaaS Product Strategy',
    alternateExpertise: 'Agile Leadership',
    pan: 'ABCDE1234F',
    aadhaar: '884729103452',
    nationalIdNumber: 'IN-8847291034',
    engagement: { talked: true, met: true, responded: false },
    marketingPreferences: { emailConsent: true, smsConsent: true, whatsappConsent: true, callConsent: false, doNotDisturb: false },
    socialMedia: { linkedin: 'https://linkedin.com/in/arjunmehta', facebook: 'https://facebook.com/arjun.mehta', instagram: 'https://instagram.com/arjunmehta', twitter: 'https://twitter.com/arjunmehta', website: 'https://arjunmehta.dev', youtube: 'https://youtube.com/@arjunmehta', telegram: 'https://t.me/arjunmehta', discord: 'https://discord.gg/arjunmehta' },
    note1: 'High-value enterprise prospect. Interested in CRM migration.',
    note2: 'Prefers email during business hours (9 AM – 6 PM IST).',
    note3: 'Referred by existing client — TechNova Solutions.',
    note4: 'Follow-up scheduled for Q2 product demo.',
    note5: 'Decision maker for procurement. Budget approved FY2024–25.',
    audit: { createdBy: 'Priya Sharma', createdDate: '2024-01-15T10:30:00', modifiedBy: 'Rahul Verma', modifiedDate: '2024-06-10T14:45:00', status: 'Active' },
  },
  {
    id: 'MOB-002',
    profilePicture: '',
    status: 'Active',
    sourceChannel: 'Referral',
    salutation: 'Ms.',
    firstName: 'Sneha',
    lastName: 'Kapoor',
    fullName: 'Ms. Sneha Kapoor',
    gender: 'Female',
    dateOfBirth: '1992-07-22',
    maritalStatus: 'Single',
    nationality: 'Indian',
    language: 'English',
    religion: 'Sikh',
    mobileNumber: '+91 99887 76655',
    alternateMobileNumber: '',
    emailAddress: 'sneha.k@techcorp.in',
    alternateEmailAddress: '',
    currentAddress: { line1: '88 MG Road', line2: 'Floor 4', line3: '', city: 'Bangalore', state: 'Karnataka', country: 'India', zipCode: '560001' },
    permanentAddressSameAsCurrent: true,
    permanentAddress: { line1: '88 MG Road', line2: 'Floor 4', line3: '', city: 'Bangalore', state: 'Karnataka', country: 'India', zipCode: '560001' },
    organization: 'TechCorp India',
    designation: 'VP Sales',
    occupation: 'Sales Leadership',
    industryType: 'Software',
    experienceYears: 10,
    experienceMonths: 3,
    primaryExpertise: 'Enterprise Sales',
    alternateExpertise: 'Channel Partnerships',
    pan: 'FGHIJ5678K',
    aadhaar: '123456789012',
    nationalIdNumber: 'IN-1234567890',
    engagement: { talked: true, met: false, responded: true },
    marketingPreferences: { emailConsent: true, smsConsent: false, whatsappConsent: true, callConsent: true, doNotDisturb: false },
    socialMedia: { linkedin: 'https://linkedin.com/in/snehakapoor', facebook: '', instagram: '', twitter: '', website: '', youtube: '', telegram: '', discord: '' },
    note1: 'Key decision maker for enterprise deal.',
    note2: '', note3: '', note4: '', note5: '',
    audit: { createdBy: 'Rahul Verma', createdDate: '2024-02-20T09:00:00', modifiedBy: 'Priya Sharma', modifiedDate: '2024-05-18T11:20:00', status: 'Active' },
  },
  {
    id: 'MOB-003',
    profilePicture: '',
    status: 'Inactive',
    sourceChannel: 'Cold Call',
    salutation: 'Dr.',
    firstName: 'Vikram',
    lastName: 'Singh',
    fullName: 'Dr. Vikram Singh',
    gender: 'Male',
    dateOfBirth: '1980-11-08',
    maritalStatus: 'Married',
    nationality: 'Indian',
    language: 'Hindi, Punjabi',
    religion: 'Sikh',
    mobileNumber: '+91 87654 32109',
    alternateMobileNumber: '+91 76543 21098',
    emailAddress: 'vikram.singh@healthplus.com',
    alternateEmailAddress: 'dr.vikram@gmail.com',
    currentAddress: { line1: '12 Medical Plaza', line2: 'Sector 44', line3: '', city: 'Chandigarh', state: 'Punjab', country: 'India', zipCode: '160047' },
    permanentAddressSameAsCurrent: false,
    permanentAddress: { line1: '5 Model Town', line2: '', line3: '', city: 'Ludhiana', state: 'Punjab', country: 'India', zipCode: '141002' },
    organization: 'HealthPlus Clinics',
    designation: 'Chief Medical Officer',
    occupation: 'Healthcare',
    industryType: 'Healthcare',
    experienceYears: 18,
    experienceMonths: 0,
    primaryExpertise: 'Clinical Operations',
    alternateExpertise: 'Healthcare IT',
    pan: 'KLMNO9012P',
    aadhaar: '987654321098',
    nationalIdNumber: 'IN-9876543210',
    engagement: { talked: false, met: false, responded: false },
    marketingPreferences: { emailConsent: false, smsConsent: false, whatsappConsent: false, callConsent: false, doNotDisturb: true },
    socialMedia: { linkedin: 'https://linkedin.com/in/vikramsingh', facebook: '', instagram: '', twitter: '', website: 'https://healthplus.com', youtube: '', telegram: '', discord: '' },
    note1: 'Not interested at this time. Revisit Q4.',
    note2: '', note3: '', note4: '', note5: '',
    audit: { createdBy: 'Admin', createdDate: '2023-11-05T14:00:00', modifiedBy: 'Admin', modifiedDate: '2024-03-01T10:00:00', status: 'Inactive' },
  },
  {
    id: 'MOB-004',
    profilePicture: '',
    status: 'Active',
    sourceChannel: 'LinkedIn',
    salutation: 'Mrs.',
    firstName: 'Ananya',
    lastName: 'Reddy',
    fullName: 'Mrs. Ananya Reddy',
    gender: 'Female',
    dateOfBirth: '1990-04-12',
    maritalStatus: 'Married',
    nationality: 'Indian',
    language: 'English, Telugu',
    religion: 'Hindu',
    mobileNumber: '+91 91234 56780',
    alternateMobileNumber: '',
    emailAddress: 'ananya.reddy@fintech.io',
    alternateEmailAddress: '',
    currentAddress: { line1: 'Tower B, Cyber Towers', line2: 'HITEC City', line3: '', city: 'Hyderabad', state: 'Telangana', country: 'India', zipCode: '500081' },
    permanentAddressSameAsCurrent: true,
    permanentAddress: { line1: 'Tower B, Cyber Towers', line2: 'HITEC City', line3: '', city: 'Hyderabad', state: 'Telangana', country: 'India', zipCode: '500081' },
    organization: 'FinTech Innovations',
    designation: 'Director of Operations',
    occupation: 'Operations',
    industryType: 'Financial Services',
    experienceYears: 14,
    experienceMonths: 8,
    primaryExpertise: 'FinOps',
    alternateExpertise: 'Regulatory Compliance',
    pan: 'PQRST3456U',
    aadhaar: '456789012345',
    nationalIdNumber: 'IN-4567890123',
    engagement: { talked: true, met: true, responded: true },
    marketingPreferences: { emailConsent: true, smsConsent: true, whatsappConsent: false, callConsent: true, doNotDisturb: false },
    socialMedia: { linkedin: 'https://linkedin.com/in/ananyareddy', facebook: '', instagram: 'https://instagram.com/ananyareddy', twitter: '', website: '', youtube: '', telegram: '', discord: '' },
    note1: 'Warm lead from LinkedIn campaign.',
    note2: 'Requested product brochure.',
    note3: '', note4: '', note5: '',
    audit: { createdBy: 'Priya Sharma', createdDate: '2024-04-01T08:30:00', modifiedBy: 'Priya Sharma', modifiedDate: '2024-06-01T16:00:00', status: 'Active' },
  },
  {
    id: 'MOB-005',
    profilePicture: '',
    status: 'Active',
    sourceChannel: 'Trade Show',
    salutation: 'Mr.',
    firstName: 'Rohan',
    lastName: 'Desai',
    fullName: 'Mr. Rohan Desai',
    gender: 'Male',
    dateOfBirth: '1985-09-30',
    maritalStatus: 'Married',
    nationality: 'Indian',
    language: 'English, Gujarati',
    religion: 'Hindu',
    mobileNumber: '+91 98760 12345',
    alternateMobileNumber: '',
    emailAddress: 'rohan.desai@manufacturing.co.in',
    alternateEmailAddress: 'rohan.d@gmail.com',
    currentAddress: { line1: 'Plot 22, GIDC Estate', line2: 'Vatva', line3: '', city: 'Ahmedabad', state: 'Gujarat', country: 'India', zipCode: '382445' },
    permanentAddressSameAsCurrent: false,
    permanentAddress: { line1: '78 Satellite Road', line2: '', line3: '', city: 'Ahmedabad', state: 'Gujarat', country: 'India', zipCode: '380015' },
    organization: 'Desai Manufacturing Co.',
    designation: 'Managing Director',
    occupation: 'Manufacturing',
    industryType: 'Manufacturing',
    experienceYears: 20,
    experienceMonths: 2,
    primaryExpertise: 'Supply Chain',
    alternateExpertise: 'Export Management',
    pan: 'UVWXY7890Z',
    aadhaar: '567890123456',
    nationalIdNumber: 'IN-5678901234',
    engagement: { talked: true, met: false, responded: true },
    marketingPreferences: { emailConsent: true, smsConsent: false, whatsappConsent: true, callConsent: true, doNotDisturb: false },
    socialMedia: { linkedin: 'https://linkedin.com/in/rohandesai', facebook: '', instagram: '', twitter: '', website: 'https://desaimfg.co.in', youtube: '', telegram: '', discord: '' },
    note1: 'Met at India Manufacturing Expo 2024.',
    note2: '', note3: '', note4: '', note5: '',
    audit: { createdBy: 'Rahul Verma', createdDate: '2024-05-10T12:00:00', modifiedBy: 'Rahul Verma', modifiedDate: '2024-05-10T12:00:00', status: 'Active' },
  },
  {
    id: 'MOB-006',
    profilePicture: '',
    status: 'Inactive',
    sourceChannel: 'Email Campaign',
    salutation: 'Ms.',
    firstName: 'Kavita',
    lastName: 'Nair',
    fullName: 'Ms. Kavita Nair',
    gender: 'Female',
    dateOfBirth: '1995-01-18',
    maritalStatus: 'Single',
    nationality: 'Indian',
    language: 'English, Malayalam',
    religion: 'Hindu',
    mobileNumber: '+91 94470 12345',
    alternateMobileNumber: '',
    emailAddress: 'kavita.nair@startup.in',
    alternateEmailAddress: '',
    currentAddress: { line1: 'Startup Hub, Kakkanad', line2: '', line3: '', city: 'Kochi', state: 'Kerala', country: 'India', zipCode: '682030' },
    permanentAddressSameAsCurrent: true,
    permanentAddress: { line1: 'Startup Hub, Kakkanad', line2: '', line3: '', city: 'Kochi', state: 'Kerala', country: 'India', zipCode: '682030' },
    organization: 'Coastal Startups',
    designation: 'Founder & CEO',
    occupation: 'Entrepreneur',
    industryType: 'Startup',
    experienceYears: 6,
    experienceMonths: 0,
    primaryExpertise: 'Product Development',
    alternateExpertise: 'Fundraising',
    pan: 'ABCPQ1234D',
    aadhaar: '678901234567',
    nationalIdNumber: 'IN-6789012345',
    engagement: { talked: false, met: false, responded: false },
    marketingPreferences: { emailConsent: true, smsConsent: false, whatsappConsent: false, callConsent: false, doNotDisturb: true },
    socialMedia: { linkedin: 'https://linkedin.com/in/kavitnair', facebook: '', instagram: '', twitter: 'https://twitter.com/kavitnair', website: '', youtube: '', telegram: '', discord: '' },
    note1: 'Unsubscribed from email list.',
    note2: '', note3: '', note4: '', note5: '',
    audit: { createdBy: 'Admin', createdDate: '2023-08-22T11:00:00', modifiedBy: 'Priya Sharma', modifiedDate: '2024-01-10T09:00:00', status: 'Inactive' },
  },
  {
    id: 'MOB-007',
    profilePicture: '',
    status: 'Active',
    sourceChannel: 'Partner Referral',
    salutation: 'Mr.',
    firstName: 'Imran',
    lastName: 'Khan',
    fullName: 'Mr. Imran Khan',
    gender: 'Male',
    dateOfBirth: '1987-06-25',
    maritalStatus: 'Married',
    nationality: 'Indian',
    language: 'English, Urdu',
    religion: 'Muslim',
    mobileNumber: '+91 98100 54321',
    alternateMobileNumber: '+91 98101 54321',
    emailAddress: 'imran.khan@retailgroup.com',
    alternateEmailAddress: '',
    currentAddress: { line1: 'Select Citywalk', line2: 'Saket', line3: 'Unit 204', city: 'Delhi', state: 'Delhi', country: 'India', zipCode: '110017' },
    permanentAddressSameAsCurrent: false,
    permanentAddress: { line1: '45 Nizamuddin East', line2: '', line3: '', city: 'Delhi', state: 'Delhi', country: 'India', zipCode: '110013' },
    organization: 'Retail Group India',
    designation: 'Head of Procurement',
    occupation: 'Retail',
    industryType: 'Retail',
    experienceYears: 15,
    experienceMonths: 4,
    primaryExpertise: 'Vendor Management',
    alternateExpertise: 'Category Management',
    pan: 'EFGHI5678J',
    aadhaar: '789012345678',
    nationalIdNumber: 'IN-7890123456',
    engagement: { talked: true, met: true, responded: true },
    marketingPreferences: { emailConsent: true, smsConsent: true, whatsappConsent: true, callConsent: true, doNotDisturb: false },
    socialMedia: { linkedin: 'https://linkedin.com/in/imrankhan', facebook: '', instagram: '', twitter: '', website: '', youtube: '', telegram: '', discord: '' },
    note1: 'Partner referral from Retail Group.',
    note2: 'Demo completed successfully.',
    note3: '', note4: '', note5: '',
    audit: { createdBy: 'Rahul Verma', createdDate: '2024-03-15T10:00:00', modifiedBy: 'Rahul Verma', modifiedDate: '2024-06-05T15:30:00', status: 'Active' },
  },
  {
    id: 'MOB-008',
    profilePicture: '',
    status: 'Active',
    sourceChannel: 'Website Lead',
    salutation: 'Ms.',
    firstName: 'Pooja',
    lastName: 'Sharma',
    fullName: 'Ms. Pooja Sharma',
    gender: 'Female',
    dateOfBirth: '1993-12-03',
    maritalStatus: 'Single',
    nationality: 'Indian',
    language: 'English, Hindi',
    religion: 'Hindu',
    mobileNumber: '+91 98765 11111',
    alternateMobileNumber: '',
    emailAddress: 'pooja.sharma@edutech.in',
    alternateEmailAddress: 'pooja.s@gmail.com',
    currentAddress: { line1: 'EduTech Park', line2: 'Salt Lake', line3: 'Block A', city: 'Kolkata', state: 'West Bengal', country: 'India', zipCode: '700091' },
    permanentAddressSameAsCurrent: true,
    permanentAddress: { line1: 'EduTech Park', line2: 'Salt Lake', line3: 'Block A', city: 'Kolkata', state: 'West Bengal', country: 'India', zipCode: '700091' },
    organization: 'EduTech Learning',
    designation: 'Head of Partnerships',
    occupation: 'EdTech',
    industryType: 'Education',
    experienceYears: 8,
    experienceMonths: 11,
    primaryExpertise: 'B2B Partnerships',
    alternateExpertise: 'Content Strategy',
    pan: 'HIJKL9012M',
    aadhaar: '890123456789',
    nationalIdNumber: 'IN-8901234567',
    engagement: { talked: true, met: false, responded: true },
    marketingPreferences: { emailConsent: true, smsConsent: true, whatsappConsent: true, callConsent: false, doNotDisturb: false },
    socialMedia: { linkedin: 'https://linkedin.com/in/poojasharma', facebook: '', instagram: 'https://instagram.com/poojasharma', twitter: '', website: '', youtube: '', telegram: '', discord: '' },
    note1: 'Interested in education sector package.',
    note2: '', note3: '', note4: '', note5: '',
    audit: { createdBy: 'Priya Sharma', createdDate: '2024-06-01T09:00:00', modifiedBy: 'Priya Sharma', modifiedDate: '2024-06-12T10:00:00', status: 'Active' },
  },
  {
    id: 'MOB-009',
    profilePicture: '',
    status: 'Active',
    sourceChannel: 'Cold Call',
    salutation: 'Mr.',
    firstName: 'Deepak',
    lastName: 'Patel',
    fullName: 'Mr. Deepak Patel',
    gender: 'Male',
    dateOfBirth: '1982-02-14',
    maritalStatus: 'Married',
    nationality: 'Indian',
    language: 'English, Gujarati, Hindi',
    religion: 'Hindu',
    mobileNumber: '+91 98250 67890',
    alternateMobileNumber: '',
    emailAddress: 'deepak.patel@logistics.in',
    alternateEmailAddress: '',
    currentAddress: { line1: 'Logistics Hub, MIDC', line2: 'Taloja', line3: '', city: 'Navi Mumbai', state: 'Maharashtra', country: 'India', zipCode: '410208' },
    permanentAddressSameAsCurrent: false,
    permanentAddress: { line1: '23 CG Road', line2: '', line3: '', city: 'Ahmedabad', state: 'Gujarat', country: 'India', zipCode: '380009' },
    organization: 'Swift Logistics',
    designation: 'Operations Director',
    occupation: 'Logistics',
    industryType: 'Transportation',
    experienceYears: 16,
    experienceMonths: 7,
    primaryExpertise: 'Fleet Management',
    alternateExpertise: 'Route Optimization',
    pan: 'MNOPQ3456R',
    aadhaar: '901234567890',
    nationalIdNumber: 'IN-9012345678',
    engagement: { talked: true, met: true, responded: false },
    marketingPreferences: { emailConsent: true, smsConsent: false, whatsappConsent: true, callConsent: true, doNotDisturb: false },
    socialMedia: { linkedin: 'https://linkedin.com/in/deepakpatel', facebook: '', instagram: '', twitter: '', website: 'https://swiftlogistics.in', youtube: '', telegram: '', discord: '' },
    note1: 'Evaluating CRM for fleet tracking integration.',
    note2: '', note3: '', note4: '', note5: '',
    audit: { createdBy: 'Rahul Verma', createdDate: '2024-04-20T14:00:00', modifiedBy: 'Rahul Verma', modifiedDate: '2024-05-30T11:00:00', status: 'Active' },
  },
  {
    id: 'MOB-010',
    profilePicture: '',
    status: 'Inactive',
    sourceChannel: 'Referral',
    salutation: 'Dr.',
    firstName: 'Meera',
    lastName: 'Iyer',
    fullName: 'Dr. Meera Iyer',
    gender: 'Female',
    dateOfBirth: '1978-08-19',
    maritalStatus: 'Married',
    nationality: 'Indian',
    language: 'English, Tamil',
    religion: 'Hindu',
    mobileNumber: '+91 98400 11223',
    alternateMobileNumber: '',
    emailAddress: 'meera.iyer@hospital.org',
    alternateEmailAddress: '',
    currentAddress: { line1: 'Apollo Hospital Campus', line2: 'Greams Road', line3: '', city: 'Chennai', state: 'Tamil Nadu', country: 'India', zipCode: '600006' },
    permanentAddressSameAsCurrent: true,
    permanentAddress: { line1: 'Apollo Hospital Campus', line2: 'Greams Road', line3: '', city: 'Chennai', state: 'Tamil Nadu', country: 'India', zipCode: '600006' },
    organization: 'Apollo Hospitals',
    designation: 'Department Head',
    occupation: 'Healthcare',
    industryType: 'Healthcare',
    experienceYears: 22,
    experienceMonths: 0,
    primaryExpertise: 'Hospital Administration',
    alternateExpertise: 'Patient CRM',
    pan: 'STUVW7890X',
    aadhaar: '012345678901',
    nationalIdNumber: 'IN-0123456789',
    engagement: { talked: false, met: true, responded: false },
    marketingPreferences: { emailConsent: false, smsConsent: false, whatsappConsent: false, callConsent: false, doNotDisturb: true },
    socialMedia: { linkedin: 'https://linkedin.com/in/meera-iyer', facebook: '', instagram: '', twitter: '', website: '', youtube: '', telegram: '', discord: '' },
    note1: 'On hold — budget freeze until next fiscal year.',
    note2: '', note3: '', note4: '', note5: '',
    audit: { createdBy: 'Admin', createdDate: '2023-06-01T10:00:00', modifiedBy: 'Admin', modifiedDate: '2024-02-28T16:00:00', status: 'Inactive' },
  },
  {
    id: 'MOB-011',
    profilePicture: '',
    status: 'Active',
    sourceChannel: 'LinkedIn',
    salutation: 'Mr.',
    firstName: 'Amit',
    lastName: 'Gupta',
    fullName: 'Mr. Amit Gupta',
    gender: 'Male',
    dateOfBirth: '1991-05-07',
    maritalStatus: 'Single',
    nationality: 'Indian',
    language: 'English, Hindi',
    religion: 'Hindu',
    mobileNumber: '+91 98111 22334',
    alternateMobileNumber: '',
    emailAddress: 'amit.gupta@saas.io',
    alternateEmailAddress: '',
    currentAddress: { line1: 'WeWork Galaxy', line2: 'Residency Road', line3: '', city: 'Bangalore', state: 'Karnataka', country: 'India', zipCode: '560025' },
    permanentAddressSameAsCurrent: true,
    permanentAddress: { line1: 'WeWork Galaxy', line2: 'Residency Road', line3: '', city: 'Bangalore', state: 'Karnataka', country: 'India', zipCode: '560025' },
    organization: 'CloudSaaS Inc',
    designation: 'CTO',
    occupation: 'Technology',
    industryType: 'SaaS',
    experienceYears: 11,
    experienceMonths: 2,
    primaryExpertise: 'Cloud Architecture',
    alternateExpertise: 'DevOps',
    pan: 'YZABC1234E',
    aadhaar: '112233445566',
    nationalIdNumber: 'IN-1122334455',
    engagement: { talked: true, met: false, responded: true },
    marketingPreferences: { emailConsent: true, smsConsent: false, whatsappConsent: true, callConsent: false, doNotDisturb: false },
    socialMedia: { linkedin: 'https://linkedin.com/in/amitgupta', facebook: '', instagram: '', twitter: 'https://twitter.com/amitgupta', website: 'https://amitgupta.dev', youtube: '', telegram: '', discord: '' },
    note1: 'Technical evaluation in progress.',
    note2: '', note3: '', note4: '', note5: '',
    audit: { createdBy: 'Priya Sharma', createdDate: '2024-06-08T11:00:00', modifiedBy: 'Priya Sharma', modifiedDate: '2024-06-13T09:00:00', status: 'Active' },
  },
  {
    id: 'MOB-012',
    profilePicture: '',
    status: 'Active',
    sourceChannel: 'Trade Show',
    salutation: 'Ms.',
    firstName: 'Lakshmi',
    lastName: 'Venkat',
    fullName: 'Ms. Lakshmi Venkat',
    gender: 'Female',
    dateOfBirth: '1989-10-28',
    maritalStatus: 'Married',
    nationality: 'Indian',
    language: 'English, Tamil, Telugu',
    religion: 'Hindu',
    mobileNumber: '+91 98480 55667',
    alternateMobileNumber: '',
    emailAddress: 'lakshmi.v@realty.com',
    alternateEmailAddress: '',
    currentAddress: { line1: 'Phoenix Towers', line2: 'Banjara Hills', line3: 'Suite 1201', city: 'Hyderabad', state: 'Telangana', country: 'India', zipCode: '500034' },
    permanentAddressSameAsCurrent: false,
    permanentAddress: { line1: '12 T Nagar', line2: '', line3: '', city: 'Chennai', state: 'Tamil Nadu', country: 'India', zipCode: '600017' },
    organization: 'Phoenix Realty',
    designation: 'Sales Director',
    occupation: 'Real Estate',
    industryType: 'Real Estate',
    experienceYears: 13,
    experienceMonths: 5,
    primaryExpertise: 'Luxury Sales',
    alternateExpertise: 'Client Relations',
    pan: 'DEFGH5678I',
    aadhaar: '223344556677',
    nationalIdNumber: 'IN-2233445566',
    engagement: { talked: true, met: true, responded: true },
    marketingPreferences: { emailConsent: true, smsConsent: true, whatsappConsent: true, callConsent: true, doNotDisturb: false },
    socialMedia: { linkedin: 'https://linkedin.com/in/lakshmivenkat', facebook: 'https://facebook.com/lakshmi.v', instagram: 'https://instagram.com/lakshmivenkat', twitter: '', website: '', youtube: '', telegram: '', discord: '' },
    note1: 'High net worth client segment.',
    note2: 'VIP treatment requested.',
    note3: '', note4: '', note5: '',
    audit: { createdBy: 'Rahul Verma', createdDate: '2024-05-25T13:00:00', modifiedBy: 'Rahul Verma', modifiedDate: '2024-06-11T17:00:00', status: 'Active' },
  },
];

function getContacts() {
  const stored = localStorage.getItem(STORAGE_KEY);
  if (stored) {
    try { return JSON.parse(stored); } catch { /* fall through */ }
  }
  localStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_CONTACTS));
  return DEFAULT_CONTACTS;
}

function saveContacts(contacts) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(contacts));
}

function getContactById(id) {
  return getContacts().find((c) => c.id === id) || null;
}

function updateContact(id, data) {
  const contacts = getContacts();
  const idx = contacts.findIndex((c) => c.id === id);
  if (idx === -1) return null;
  contacts[idx] = { ...contacts[idx], ...data };
  saveContacts(contacts);
  return contacts[idx];
}

function deleteContact(id) {
  const contacts = getContacts();
  const idx = contacts.findIndex((c) => c.id === id);
  if (idx === -1) return false;
  contacts[idx].status = 'Inactive';
  contacts[idx].audit = {
    ...contacts[idx].audit,
    status: 'Inactive',
    modifiedBy: 'Current User',
    modifiedDate: new Date().toISOString(),
  };
  saveContacts(contacts);
  return true;
}

function createContact(partial) {
  const contacts = getContacts();
  const num = contacts.length + 1;
  const id = `MOB-${String(num).padStart(3, '0')}`;
  const now = new Date().toISOString();
  const contact = {
    ...DEFAULT_CONTACTS[0],
    ...partial,
    id,
    audit: {
      createdBy: 'Current User',
      createdDate: now,
      modifiedBy: 'Current User',
      modifiedDate: now,
      status: partial.status || 'Active',
    },
  };
  contacts.push(contact);
  saveContacts(contacts);
  return contact;
}

function formatDate(iso) {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function formatDateTime(iso) {
  if (!iso) return '—';
  return new Date(iso).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
}

function getInitials(name) {
  return name.replace(/^(Mr\.|Mrs\.|Ms\.|Dr\.|Prof\.)\s*/i, '').split(' ').map((n) => n[0]).join('').slice(0, 2).toUpperCase();
}

function maskValue(value, visible = 4) {
  if (!value) return '';
  if (value.length <= visible) return '••••';
  return '•'.repeat(value.length - visible) + value.slice(-visible);
}

function maskPan(value) {
  if (!value || value.length < 10) return 'XXXXX•••••';
  return `XXXXX${value.substring(5, 9)}X`;
}

function maskAadhaar(value) {
  const d = String(value).replace(/\D/g, '');
  if (d.length < 4) return 'XXXX-XXXX-••••';
  return `XXXX-XXXX-${d.slice(-4)}`;
}

function stripPhone(value) {
  return String(value || '').replace(/^\+91\s*/, '').trim();
}

function buildFullName(salutation, firstName, lastName) {
  return [salutation, firstName, lastName].filter(Boolean).join(' ').replace(/\s+/g, ' ').trim();
}
